openapi: '3.0.2'
info:
  title: SIPEJU Api Documentation
  version: '1.0'
servers:
  - url: http://127.0.0.1:8000/api
  - url: https://developmentprogres.judulkustmikadhiguna.xyz
paths:

  /mahasiswa:
    post:
      tags:
        - "Mahasiswa"
      summary: "Post Data Mahasiswa"
      description: 'Insert new data to mahasiswa table'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nama:
                  type: string
                nim:
                  type: number
                  example: "05520117043"
                jurusan:
                  type: string
                hp:
                  type: number
                  example: "081222202202"
                alamat:
                  type: string
                jk:
                  type: string
                angkatan:
                  type: string
                kelas:
                  type: string
      parameters: []
      responses:
        '201':
          description: OK

  /mahasiswa/{mahasiswa_id}:
    get:
      tags:
        - "Mahasiswa"
      summary: Get Mahasiswa By Id
      description: 'This endpoint to get mahasiswa by id'
      parameters: 
        - in: path
          name: mahasiswa_id
          schema:
            type: integer
          required: true
          description: numeric ID
      responses:
        '200':
          description: OK

    patch:
      tags:
        - "Mahasiswa"
      summary: Update Mahasiswa By Id
      description: 'This endpoint to get mahasiswa by id'
      parameters: 
        - in: path
          name: mahasiswa_id
          schema:
            type: integer
          required: true
          description: numeric ID
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nama:
                  type: string
                nim:
                  type: number
                  example: "05520117043"
                jurusan:
                  type: string
                hp:
                  type: number
                  example: "081222202202"
                alamat:
                  type: string
                jk:
                  type: string
                angkatan:
                  type: string
                kelas:
                  type: string
      responses:
        '200':
          description: OK
    delete:
      tags:
        - "Mahasiswa"
      summary: Delete Mahasiswa By Id
      description: 'This endpoint to delete mahasiswa by id'
      parameters: 
        - in : path
          name: mahasiswa_id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: OK

  /dosen:
    post:
      tags:
        - "Dosen"
      summary: "Post Data Dosen"
      description: 'Insert new data to dosen table'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nama:
                  type: string
                NIDN:
                  type: number
                  example: 522433
                jabatan:
                  type: string
      parameters: []
      responses:
        '200':
          description: OK
          
  /dosen/{dosen_id}:
    get:
      tags:
        - "Dosen"
      summary: Get dosen by id
      description: 'This endpoint to get dosen by id'
      parameters:
        - in : path
          name: dosen_id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: OK

    patch:
      tags:
        - "Dosen"
      summary: Update Dosen By Id
      description: 'This endpoint to get dosen by id'
      parameters:
        - in : path
          name: dosen_id
          schema:
            type: integer
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nama:
                  type: string
                NIDN:
                  type: number
                  example: 522433
                jabatan:
                  type: string
      responses:
        '200':
          description: OK

    delete:
      tags:
        - "Dosen"
      summary: Delete Dosen By Id
      description: 'This endpoint to delete dosen by id'
      parameters:
        - in : path
          name: dosen_id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: OK

  /sistem_informasi:
    post:
      tags:
        - "Sistem Informasi"
      summary: "Post Data Sistem Informasi"
      description: 'Insert new data to sistem informasi table'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                tgl_buka:
                  type: string
                  format: date
                tgl_tutup:
                  type: string
                  format: date
                sesi:
                  type: number
                  example: 1
                persyaratan:
                  type: string
      parameters: []
      responses:
        '200':
          description: OK

  /sistem_informasi/{SI_id}:
    get:
      tags:
        - "Sistem Informasi"
      summary: Get sistem informasi by id
      description: 'This endpoint to get sistem informasi by id'
      parameters:
        - in : path
          name: SI_id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: OK

    patch:
      tags:
        - "Sistem Informasi"
      summary: "Update Data Sistem Informasi"
      description: 'Update data to sistem informasi table'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                tgl_buka:
                  type: string
                  format: date
                tgl_tutup:
                  type: string
                  format: date
                sesi:
                  type: number
                  example: 1
                persyaratan:
                  type: string
      parameters:
        - in : path
          name: SI_id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: OK

    delete:
      tags:
        - "Sistem Informasi"
      summary: "Delete Data Sistem Informasi"
      description: 'Delete data to sistem informasi table'
      parameters:
        - in : path
          name: SI_id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: OK

  /admin:
    post:
      tags:
        - "Admin"
      summary: "Post Data Admin"
      description: 'Post data to admin table'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nama:
                  type: string
                jabatan:
                  type: string
                nidn:
                  type: number
                  example: 4435533
      parameters: []
      responses:
        '200':
          description: OK

  /admin/{admin_id}:
    get:
      tags:
        - "Admin"
      summary: "Get Data Admin"
      description: 'Get data from admin table'
      parameters:
        - in : path
          name: admin_id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: OK

    patch:
      tags:
        - "Admin"
      summary: "Update Data Admin"
      description: 'Update data to admin table'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nama:
                  type: string
                jabatan:
                  type: string
                nidn:
                  type: number
                  example: 4435533
      parameters:
        - in : path
          name: admin_id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: OK

    delete:
      tags:
        - "Admin"
      summary: "Delete Data Admin"
      description: 'Delete data from admin table'
      parameters:
        - in : path
          name: admin_id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: OK


    
