openapi: '3.0.2'
info:
  title: SIPEJU Api Documentation
  version: '1.0'
servers:
  - url: http://127.0.0.1:8000/api
paths:

  /mahasiswa:
    post:
      tags:
        - "Mahasiswa"
      summary: "Post Data Mahasiswa"
      description: 'Insert new data to mahasiswa table'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nama:
                  type: string
                nim:
                  type: number
                  example: "05520117043"
                jurusan:
                  type: string
                hp:
                  type: number
                  example: "081222202202"
                alamat:
                  type: string
                jk:
                  type: string
                angkatan:
                  type: string
                kelas:
                  type: string
      parameters: []
      responses:
        '201':
          description: OK

  /mahasiswa/{mahasiswa_id}:
    get:
      tags:
        - "Mahasiswa"
      summary: Get Mahasiswa By Id
      description: 'This endpoint to get mahasiswa by id'
      parameters: 
        - in: path
          name: mahasiswa_id
          schema:
            type: integer
          required: true
          description: numeric ID
      responses:
        '200':
          description: OK

    patch:
      tags:
        - "Mahasiswa"
      summary: Update Mahasiswa By Id
      description: 'This endpoint to get mahasiswa by id'
      parameters: 
        - in: path
          name: mahasiswa_id
          schema:
            type: integer
          required: true
          description: numeric ID
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nama:
                  type: string
                nim:
                  type: number
                  example: "05520117043"
                jurusan:
                  type: string
                hp:
                  type: number
                  example: "081222202202"
                alamat:
                  type: string
                jk:
                  type: string
                angkatan:
                  type: string
                kelas:
                  type: string
      responses:
        '200':
          description: OK
    delete:
      tags:
        - "Mahasiswa"
      summary: Delete Mahasiswa By Id
      description: 'This endpoint to delete mahasiswa by id'
      parameters: 
        - in : path
          name: mahasiswa_id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: OK

  /dosen:
    post:
      tags:
        - "Dosen"
      summary: "Post Data Dosen"
      description: 'Insert new data to dosen table'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nama:
                  type: string
                NIDN:
                  type: number
                  example: 522433
                jabatan:
                  type: string
      parameters: []
      responses:
        '200':
          description: OK
          
  /dosen/{dosen_id}:
    get:
      tags:
        - "Dosen"
      summary: Get dosen by id
      description: 'This endpoint to get dosen by id'
      parameters:
        - in : path
          name: dosen_id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: OK

    patch:
      tags:
        - "Dosen"
      summary: Update Dosen By Id
      description: 'This endpoint to get dosen by id'
      parameters:
        - in : path
          name: dosen_id
          schema:
            type: integer
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nama:
                  type: string
                NIDN:
                  type: number
                  example: 522433
                jabatan:
                  type: string
      responses:
        '200':
          description: OK


    
